### ISSUE TITLE
Can't open requirements.txt

### ISSUE THREAD

**Issue by djokenzi** [ilyakharlamov/bookmate_downloader#1]
$ pip install -r requirements.txt

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by ilyakharlamov** [comment]
fixed

**Comment by djokenzi** [comment]
Thanks for the prompt response! 

It doesn't work on win10, though... I can't install pycrypto...

**Comment by ilyakharlamov** [comment]
@djokenzi I don't have a windows machine to test.
It definitely works on Mac OS X,
it may also work on Linux and WSL (Windows Linux Subsystem)

**Comment by djokenzi** [comment]
It works on Ubuntu! I had to install some libraries manually, but it definitely works. 

Thank you sir!
