### ISSUE TITLE
ValueError: Namespace Secret not available

### ISSUE THREAD

**Issue by immanueldej** [ilyakharlamov/bookmate_downloader#2]
Hello! I'm having this issue with the code. I don't know a lot about pyton so I had so difficulties to get to this point. Thanks in advance! 

![image](https://user-images.githubusercontent.com/64808829/81011004-d1e69700-8e1c-11ea-9a53-7943e974db34.png)

**Comment by ilyakharlamov** [comment]
Hi Immanuel
I've updated the script so that it will ask for the browser cookie if it cannot find it in your browser.
do `git pull` and try again

**Comment by immanueldej** [comment]
Hey, it worked!. Thank you a lot. I really apriciate it.
