### ISSUE TITLE
Turkish Books

### ISSUE THREAD

**Issue by rasitozdemir** [ilyakharlamov/bookmate_downloader#3]
Thanks for codes.. Turkish books are not downloaded.
![code](https://user-images.githubusercontent.com/39971664/83681991-ee2c4e00-a5eb-11ea-8325-092e67c2fadd.jpg)

**Comment by antboj** [comment]
I have the same problem for Serbian books

**Comment by ilyakharlamov** [comment]
@antboj @rasitozdemir 
I made a few fixes, maybe it will work now.
I don't have a paid subscription at the moment so I cannot check.
If you have any free book that is causing the problem you can let me know.
