### ISSUE TITLE
Error on Book Download

### ISSUE THREAD

**Issue by TobiasMende** [ilyakharlamov/bookmate_downloader#4]
Hello, thank you for this project.

Unfortunately, I have problems downloading a book with this script:

```ERROR bookmate_downloader.process_opf():191  cannot download from 'https://reader.bookmate.com/p/a/4/d/dJAgbfVH/contents/OEBPS/cover.jpg'```

I tried different books (i.e. this one: https://reader.bookmate.com/fDd3Kbpv )

`python3 src/python3/bookmate_downloader.py --bookid fDd3Kbpv` on Mac OS X.

Do you have an idea, what the problem could be?

Thanks 🙏

**Comment by ilyakharlamov** [comment]
@TobiasMende 
Check the 'out' folder, the downloaded book should be there anyway.

**Comment by TobiasMende** [comment]
@ilyakharlamov Thanks for the quick response. Yes it is there but only a couple of KBs big and if I import it lets say into iBooks, it says, that the book is corrupt. 🤔

**Comment by TobiasMende** [comment]
@ilyakharlamov I just found out, that it works with Calibre. I can import the books there and read them or convert them into MOBI to read them on the Kindle.

Thanks a lot! :-)
