### ISSUE TITLE
Is possible to adapt the code to Perlego?

### ISSUE THREAD

**Issue by alexlazk** [ilyakharlamov/bookmate_downloader#6]
I'm a personal fan of this script. Recently I've discovered Perlego, which has a great collection that compliment the one of Bookmate. I think their system is quite similar to bookmate. It would be possible to make a version adapted to this service?

**Comment by ilyakharlamov** [comment]
if you can provide me the account credentials, then I can take a look.

**Comment by alexlazk** [comment]
Of course! Thanks for your response! If you could give a telegram or an anonymous mail I could contact you, I've already guessed many things, the automation is my missing part of the equation..

**Comment by jaan143** [comment]
@ilyakharlamov  dear i tried to find your email address where i want to contact you for a private paid project
if you can give me your any contact i have a project i will pay you for it
thanks 
let me know then i will give you my email here

**Comment by ilyakharlamov** [comment]
@jaan143 invited you to a private repository, see here https://github.com/ilyakharlamov/exchange_private_messages_here_1

**Comment by jaan143** [comment]
@ilyakharlamov  email sent kindly check
